index.html

mantained -> maintained, bit of a Freudian slip there? :P

Fixing a spelling mistake

---

index.html

Adds two more awesome apps to the open source section.
/cc @maxogden should it be `Friends` or `FRIENDS`?
/cc @mick

Add Friends and Geojsonapp

---

_docs/v0.26.0/api/browser-window.md
_docs/v0.26.0/api/clipboard.md
_docs/v0.26.0/api/dialog.md
_docs/v0.26.0/api/frameless-window.md
_docs/v0.26.0/api/global-shortcut.md
_docs/v0.26.0/api/ipc-main-process.md
_docs/v0.26.0/api/ipc-renderer.md
_docs/v0.26.0/api/menu-item.md
_docs/v0.26.0/api/menu.md
_docs/v0.26.0/api/remote.md
_docs/v0.26.0/api/synopsis.md
_docs/v0.26.0/api/tray.md
_docs/v0.26.0/api/web-view-tag.md
_docs/v0.26.0/tutorial/application-distribution.md
_docs/v0.26.0/tutorial/quick-start.md

This updates the docs to use absolute links :link:

Update v0.26.0 Docs

---

_docs/v0.24.0/api/browser-window.md
_docs/v0.24.0/api/clipboard.md
_docs/v0.24.0/api/dialog.md
_docs/v0.24.0/api/frameless-window.md
_docs/v0.24.0/api/global-shortcut.md
_docs/v0.24.0/api/ipc-main-process.md
_docs/v0.24.0/api/ipc-renderer.md
_docs/v0.24.0/api/menu-item.md
_docs/v0.24.0/api/menu.md
_docs/v0.24.0/api/remote.md
_docs/v0.24.0/api/synopsis.md
_docs/v0.24.0/api/tray.md
_docs/v0.24.0/api/web-view-tag.md
_docs/v0.24.0/tutorial/application-distribution.md
_docs/v0.24.0/tutorial/quick-start.md

This updates the docs to use absolute links :link:

Update v0.24.0 Docs

---

all.md

Fixes the filter used for the /all page :tangerine: 
Also, lol `fix-all` branch.

Improve Filter for /all Page

---

index.html

Adds @muan's [emojibar](https://github.com/muan/mojibar) and [yeoman-app](https://github.com/yeoman/yeoman-app)

Add more open source

---

css/pygments.css

For better contrast :moon: 
Before:
After:
Fixes https://github.com/atom/electron.atom.io/issues/41

Change Syntax Highlighting

---

css/main.css

Scroll appears even when you do not need.

---

index.html

Adding the open source note taking / organizing (Evernote-like) app [Laverna](https://laverna.cc) as they just added Electron support. It's not mentioned on their site yet, but is on [their Github releases](https://github.com/Laverna/laverna/releases/tag/0.7.0)

added Laverna to list

---

index.html

Typo fix mardown -> Markdown

---

index.html

I added a personal project to the list of open source apps built on Electron

New open source app example

---

CONTRIBUTING.md

Hopefully this will help reduce the work required by the team to manage incoming submissions.
What do you think, @jlord?

add notes about how to submit an app to the homepage list

---

index.html

Fix indent

---

_includes/head.html

Adding site verification data for Google. :tada:

Update head data with Google meta tag

---

_includes/head.html

Updating the verification tag for Google.  🙈  :computer:

Update Google verification tag

---

CONTRIBUTING.md
lib/fetch-docs.js

App icons should 256x256 and PNGs.

Document image requirements

---

_docs/api/menu.md

Fixes https://github.com/electron/electron/issues/5507

Properly capitalize Menu

---

_data/apps.yml
_includes/featured_app.html

Add app description to title attr in app grid

---

_data/apps.yml

Included 3 small fixes to the external links for the 3 latest apps actually work.

Website/Repository URL fixes

---

_data/awesome_electron.json
package.json
script/docs

This update:
- brings in new goodies that have been added to the awesome-electron repo in the last 6 weeks or so
- updates the build process to be more streamy
- adds some contributing docs
cc @kevinsawicki @jlord

update awesome-electron to 2.0

---

_pages/community.html

This will allow us to deep-link to http://electron.atom.io/community#boilerplates, etc.
⚓ 
@jlord

add ids to headings on community page

---

_data/awesome_electron.json
package.json

New stuff:
- 7 apps
- 2 boilerplates
- 3 tools
- 2 articles
- 2 videos
- 1 podcast
cc @sindresorhus

update awesome-electron to 2.1.1

---

_posts/2016-07-26-electron-podcasts.md

This PR adds a new blog post on the recent podcasts the Electron team has done.

Add a blog post on recent podcasts

---

_data/apps.yml

@zeke Hey buddy , we are already in the List , but did a typo , sorry , please merge this again ?
Thanks in advance!

Typo Fixed

---

_posts/2016-07-28-electron-internals-node-integration.md

This is the first post of a series that explains the internals of Electron.

Add blog post on node integration

---

_posts/2016-07-28-electron-internals-node-integration.md

http://stackoverflow.com/questions/10963002/jekyll-new-posts-not-being-generated

We can't have colon in title

---

_posts/2016-08-04-jully-2016-roundup.md

This is the first of a serious of mostly roundup posts features new apps, meetups and the like ✨

Add July roundup post

---

_data/apps.yml
spec/featured-spec.js

This bumps the number of featured apps on the homepage from 16 to 20.
@jlord @kevinsawicki

feature more apps on the homepage

---

_data/awesome_electron.json
package.json

HyperTerm, DevTools installer, and more!

awesome new stuff

---

_posts/2016-07-29-npm-install-electron.md

add electron-prebuilt post

---

_data/apps.yml

This fixes an image name that was incorrect. Thanks for the 👀 @Menci. 
🔗 https://github.com/electron/electron.atom.io/pull/436#issuecomment-241185620

Fix incorrect filename

---

_posts/2016-08-23-accessibility-tools.md

This is a blog post on the accessibility features that have been added to Spectron and Devtron ⭐

Add accessibility blog post

---

_data/apps.yml
_posts/2016-09-06-august-2016-roundup.md

This is a blog post listing the apps added to the site in August :sparkles: :computer:

August App Roundups 

---

CONTRIBUTING.md

This PR updates the `CONTRIBUTING.md` document to add a couple of notes on common things we need to ask when reviewing app submissions:
- In the pull request, make clear if you are involved with the project or have the OK from the project to add the site (we want to make sure teams are aware and OK with their project being added).
- Delete empty optional fields rather than leaving empty strings like `repository: " "`
🍕 🍍

Update CONTRIBUTING.md for adding applications 

---

_posts/2016-08-25-electron-internals-weak-references.md

This post introduces what is weak reference and how it is used to manage resources in Electron.

Electron Internals: Weak References

---

CONTRIBUTING.md

Sometimes I forget these things. This little checklist should help.

add blog posts section to contributing doc

---

_posts/2016-09-27-api-docs-json-schema.md

This is ready for eyes!
👀  @jlord @kevinsawicki

New post: Electron's API Docs as Structured Data

---

_posts/2015-04-23-electron.md
_posts/2015-06-04-electron-doumentation.md
_posts/2015-10-15-2015-whats-new-in-electron.md
_posts/2015-11-05-electron-updates-mac-app-store-and-windows-auto-updater.md
_posts/2015-11-17-electron-api-changes.md
_posts/2016-03-25-electron-37.md
script/releases

update atom/electron URLs to electron/electron

---

lib/doc-links.js

tiny refactor 🔍 
@kevinsawicki

remove redundant link fixing

---

script/versions

Update index.json URL

---

_data/awesome_electron.json
package.json

Brings in the latest goodies from https://github.com/sindresorhus/awesome-electron
Context for the uninitiated (@groundwater): We maintain a branch https://github.com/sindresorhus/awesome-electron/tree/npm-module for slurping up all the README content into a structured format, then publishing to npm.
Every once in a while I update this package and bring the changes into this repo, and they content is displayed on this page: http://electron.atom.io/community/
Details on how the package is updated can be found here: https://github.com/sindresorhus/awesome-electron/blob/npm-module/contributing.md#building-and-publishing-the-npm-package

update awesome electron

---

_data/apps.yml

Please contact aidan@getflow.com for verification.

Update Flow App's URL

---

_posts/2016-12-09-certificate-transparency-fix.md
script/server

Fix table styles in Certificate Transparency Fix post

---

script/release

This breaks up the release script a bit so that each build step is run and committed atomically. This will make for a nicer git commit history.
📜

Release Granularly

---

_includes/userland_footer.html
_posts/2016-12-20-userland.md
_sass/_base.scss

A followup to the design work in https://github.com/electron/electron.atom.io/pull/617
This is ready for review. Would like to publish it Tuesday (tomorrow) around 10am Pacific.
cc @electron/maintainers

Userland Blog Post

---

_includes/userland_report.html

fix placeholder text

---

_posts/2016-10-06-september-2016-roundup.md

fix image source in september roundup post

---

.travis.yml
_includes/listed_app.html
_pages/apps.html
_sass/_home.scss

This is a work in progress. Has some funky styles that need to be cleaned up.
cc @simurai

[WIP] Apps List

---

_posts/2016-12-27-electron-samples.md
_posts/2017-01-19-simple-samples.md

@kevinsawicki created these nice little apps for the Hackbright hackathon at HQ last week.
Why not share them with the world? 🌏 
Rendered: https://github.com/electron/electron.atom.io/blob/15b24ea213f277be744570569b4a9b5d393315a5/_posts/2016-12-27-electron-samples.md

add electron-samples post

---

_posts/2017-01-31-kap.md

This is the first PotW post! Planning to ship it Tuesday morning, around 10am PST.
cc @skllcrn @CodeTheory @matheuss @sindresorhus @malept
[![Kap Screenshot](https://cloud.githubusercontent.com/assets/2289/22437616/8940f53e-e6dd-11e6-872b-dec675a503c1.png)](https://getkap.co/)

Project of the Week: Kap

---

_posts/2017-02-08-beaker-browser.md

Project of the Week: Beaker Browser

---

_posts/2017-02-21-dat.md

Preview at https://zeke.github.io/electron.atom.io/blog/2017/02/21/dat

Project of the Week: Dat

---

_posts/2017-02-28-wordpress.md

Thanks to @mkaz and @johngodley for making this happen!

Project of the Week: Wordpress Desktop

---

lib/doc.js
package.json
test.js

Inject a DO NOT EDIT comment atop imported docs

---

_posts/2017-03-07-voltra.md

Project of the Week: Voltra

---

_posts/2017-03-08-touch-bar-support.md

Post about the touch bar API in 1.6.3

Add touch bar post

---

_posts/2017-03-14-webtorrent.md

Staging URL: https://zeke.github.io/electron.atom.io/blog/2017/03/14/webtorrent
🎉

Project of the Week: Webtorrent

---

lib/doc-edit-warning.txt
lib/doc.js
package.json

```                                                                                
::::                                      
:o+//+o:                                    
+o    oo-                                   
:o+//oo/+o/                                 
-::-   -oo:                               
/s/                              
-::::::::-                :s/  :::--                      
:+oo+////////+:        -:/+oo/ :s:-///++oo+:                  
/o+:                -/+oo+/:-     +o-      -:+o:                
/s:              -:+o+/:           -o+         :s/               
-s/            -/oo/:                /s-         +s-              
-s/         -/oo/-                   -s/         /s-              
oo       :+o/-                       oo         oo               
-s/ …
```

Bigger doc edit warning

---

_includes/featured_app.html
_includes/listed_app.html
_layouts/docs.html
_layouts/post.html
_layouts/releases.html
_pages/apps.html
_pages/community.html
_pages/index.html

Fixes #732 
cc @sarabreeding @bnb @CodeTheory @EdOverflow

prevent tabnabbing by remove target _blank from all links

---

_includes/head.html

I want to link out from YouTub to the site, but we need to verify ownership first.
We may be able to remove this after the fact.

Verify Site Ownership (For Youtube)

---

_includes/head.html

Fix Quotes in Site Verification

---

_includes/listed_app.html
_includes/userland_report.html
_sass/_base.scss
_sass/_basecoat-navigation.scss
_sass/_highlight.scss
_sass/_home.scss
_sass/_variables.scss

This PR makes sure the colors have enough contrast.
Closes #746 
Audit violations due to color contrast

Improve contrast

---

package-lock.json
package.json

Same thing as https://github.com/electron/electron/pull/9989

check for leaks before npm pack or git push

---

server.js
test/index.js

Fixes https://github.com/electron/electron.atom.io/issues/638 in #758

Redirect old docs URLS

---

data/blog/chromium-rce-vulnerability.md
data/blog/july-2016-roundup.md
data/blog/typescript.md

Adds the last two blog posts so that we're up to date.

Move over last missing blog posts

---

CONTRIBUTING.md
middleware/context-builder.js
package-lock.json
package.json
routes/apps/show.js
routes/docs/show.js
test/index.js
views/layouts/post.html
views/partials/head.html

Just making sure we're properly settings title and meta tags.

Test title and meta tags

---

.travis.yml
CONTRIBUTING.md
data/locale.yml
package-lock.json
routes/docs/all.js
routes/docs/category.js
server.js
styles/_basecoat-page-headers.scss
styles/_docs.scss
styles/_variables.scss
test/index.js
views/docs/all.html
views/docs/api.html
views/docs/index.html
views/layouts/docs.html

This PR implements the `/docs/all` route which displays everything on a single page. This PR also localizes more of the content and improves docs index styles.

All the Docs!

---

data/locale.yml
middleware/context-builder.js
package-lock.json
package.json
routes/languages/index.js
test/index.js
views/languages/index.html

This PR adds some design improvements to the languages page:
At last, an opportunity to use the HTML `<progress>` element. Achievement unlocked.

feat: improve the languages page

---

styles/_languages.scss
styles/index.scss
views/languages/index.html

Makes the progress bars look a bit fancier 😆

Stylize the language progress bars

---

data/blog/chromium-rce-vulnerability.md
data/blog/jasper.md
data/blog/typescript.md
data/locale.yml
middleware/blog.js
package-lock.json
package.json
views/posts/index.html
views/posts/show.html

- Update the blog section with the old look with excerpts to be more readable
- Some small changes to the blog postsl, since some formats used are not compatible with the new markdown parser we're using
- re-pin the primer-breadcrumb to a version that does not break the site (see primer/primer-css#317)
Some pending items:

Blog update [WIP]

---

CODE_OF_CONDUCT.md
README.md

Yup.
cc @vanessayuenn @codebytere

Add CoC and update README

---

styles/_basecoat-code.scss

Remove some unused styles and improve code block margin.

Code styles

---

routes/docs/category.js
routes/docs/show.js
test/index.js
views/layouts/docs.html

Like: https://electron.atom.io/docs/glossary/
All: https://github.com/electron/electron-i18n/tree/master/content/en-US/docs /*.md

Catch contents aren't subcategory of docs

---

test/index.js

Tests for the community route were scattered in the file. This PR brings them together in the same test block.

fix community tests

---

data/locale.yml
test/index.js
views/partials/footer.html

A redo of https://github.com/electron/electron.atom.io/pull/796 for the new site.
cc @lee-dohm

link to code of conduct from footer

---

data/blog/new-website.md
middleware/blog.js
package.json
scripts/platform-specific-content.js
styles/_basecoat-navigation.scss
styles/_blog.scss
views/layouts/post.html

https://electron-website-pr-835.herokuapp.com/blog/new-website

new site blog post

---

styles/_basecoat-navigation.scss

This PR fixes a spacing regression in the nav.

fix nav margin bug

---

data/blog/new-website.md

fix jekyll typo in new site blog post

---

scripts/update-demo-app-download-link.js

rewrite API Demo download link only if platform is discovered

---

styles/_userland.scss

Change CSS of userland layout

---

package.json

lock awesome-electron so greenkeeper will pick it up

---

routes/apps/index.js

Edit way to select selected category

---

server.js

Redirect /docs/latest/* to /docs/*

---

data/blog/electron-2-semantic-boogaloo.md

Short but sweet
https://electron-website-pr-940.herokuapp.com/blog/electron-2-semantic-boogaloo

Electron 2.0 and New Versioning Policy Blog Post

---

styles/_home.scss

Fix line break at electron-versions

---

views/home.html
views/partials/header.html

I fixed two errors in the templates.

Fix invalid html

---

routes/docs/history.js
views/docs/history.html

handle docs that have no history

---

package-lock.json
package.json
routes/search/operations.js
routes/search/resolvers.js
routes/search/schema.js

sort npm packages search results based on sourcerank

---

data/blog/protocol-handler-fix.md

http://electron-website-pr-1032.herokuapp.com/blog/protocol-handler-fix

add protocol handler post

---

data/locale.yml
package-lock.json
routes/search/index.js
routes/search/operations.js
server.js
styles/_search.scss
test/index.js
views/home.html
views/partials/header.html
views/partials/search/docs.html
views/partials/search/npm-packages.html
views/partials/search/repos.html
views/search.html

This will make the `/search` route accessible to public! 🎉  Also, I improved the description a bit to be more explicit about which data source the users are searching within.

Link to search from nav bar

---

package.json

fix(package): update electron-apps to version 1.2295.0

---

scripts/index.js
views/apps/show.html
views/layouts/main.html
views/partials/footer.html
views/partials/head.html

Fix #1067, related to #1068.
Compare with https://electron-website-pr-1068.herokuapp.com/

Move scripts to footer and define scripts for app

---

package.json

Fixes https://github.com/electron/electronjs.org/issues/1070

bump electron-releases

---

package.json

fix(package): update electron-apps to version 1.2348.0

---

data/locale.yml
views/search.html

Fix search page descriptions

---

package.json

fix(package): update electron-i18n to version 0.89.0

---

data/blog/website-hiccups.md

Rendered: https://electron-website-pr-1091.herokuapp.com/blog/website-hiccups
cc @MarshallOfSound are you cool with the forge recommendation in here?

website hiccups blog post

---

package.json

fix(package): update electron-i18n to version 0.99.0

---

routes/search/index.js
test/index.js

Add handling for other graphql errors.

General search errors handling

---

CONTRIBUTING.md

document crowdin proxy

---

package.json

fix(package): update electron-apps to version 1.2355.0

---

package.json

fix(package): update electron-i18n to version 0.106.0

---

package.json

fix(package): update electron-apps to version 1.2360.0

---

package.json

fix(package): update electron-i18n to version 0.109.0

---

package.json

fix(package): update electron-i18n to version 0.111.0

---

package.json

fix(package): update electron-apps to version 1.2367.0

---

middleware/lang-resolver.js
server.js
test/index.js

@zeke, Would you have a look at this new middleware to resolve the lang?

redirect the request with the correct lang #1107

---

package.json

fix(package): update electron-apps to version 1.2373.0

---

package.json

fix(package): update electron-apps to version 1.2389.0

---

package.json

fix(package): update electron-i18n to version 0.119.0

---

package.json

Pulls in changes from https://github.com/electron/electron-releases/pull/7

use new electron-releases with changelog fixes

---

package.json

fix(package): update electron-apps to version 1.2410.0

---

package.json

fix(package): update electron-i18n to version 0.145.0

---

package.json

fix(package): update electron-apps to version 1.2470.0

---

package.json

fix(package): update electron-i18n to version 0.150.1

---

package.json

fix(package): update electron-releases to version 2.15.0

---

package.json

fix(package): update electron-releases to version 2.17.0

---

package-lock.json
package.json

We don't appear to actually use this package anywhere in the code. Closes #1191.

remove github dependencies

---

package.json

fix(package): update electron-apps to version 1.2490.0

---

package.json

fix(package): update electron-apps to version 1.2497.0

---

data/blog/in-app-purchases.md

Made some progress on this today, but I'm not totally happy with it yet. Feedback, please!
@AdrienFery @codebytere @vanessayuenn @ckerr @groundwater

In-app purchases blog post

---

data/meetups.json

founder is exploring electron + pixijs as a cross-platform engine

adding PVGD due to topical nature

---

script/update-deps.sh

This will make it easier to peruse https://github.com/electron/electronjs.org/commits/master and see what's been getting updated.

update known deps granularly

---

script/update-deps.sh

This is a followup to #1230 that resolves #1237 
cc @ckerr

use a proper bash array in dep update script

---

data/blog/autoupdating-electron-apps.md

add autoupdating-electron-apps draft

---

data/blog/electron-2-0.md

Fix broken link in Electron 2.0.0 blog post

---

package-lock.json
package.json
script/update-deps.sh

This may make the `update-deps` script a little faster.

use npm ci

---

package-lock.json
package.json
scripts/search.js
styles/_search.scss
templates/api.html
templates/app.html
templates/empty.html
templates/package.html
templates/tutorial.html
views/layouts/main.html
views/partials/header.html

This PR adds the new [search-with-your-keyboard](https://github.com/electron/search-with-your-keyboard) module.
Key | Action
--- | ------
<kbd>/</kbd> | Focuses the search input.
<kbd>esc</kbd> | Focuses the search input and clears it.
<kbd>down</kbd> | Adds an `active` class to the next result.
<kbd>up</kbd> | Adds an `active` class to the previous result. If already on the first search result, the search input is focused.
<kbd>enter</kbd> | Sets `window.location` to the `href` of the first `<a>` tag in the current `.active` result, if present.
I snuck in a a few other changes too, like style tweaks and a change to the search order.

search with your keyboard

---

nodemon.json
scripts/search.js
styles/_search.scss
templates/api.html
templates/app.html
templates/index.js
templates/package.html
templates/readme.md
templates/tutorial.html
views/layouts/main.html

@echjordan see the commit messages for a summary of what's changed in this PR.

Search updates

---

data/blog/search.md

https://electron-website-pr-1283.herokuapp.com/blog/search
// @echjordan @vanessayuenn

search blog post

---

data/locale.yml
views/partials/header.html

I added ability to translate placeholder in search bar to another languages.

Search placeholder is now translable.

---

data/blog/web-preferences-fix.md

fix: use better contrastsecurity.com URL

---

middleware/browserify.js
package.json

Fixes https://github.com/electron/electronjs.org/issues/1320

fix: add missing 'pluralize' module

---

package-lock.json
script/update-deps.sh

fix: do not use "npm ci" command

---

package-lock.json
package.json

A test to see if the latest version of `electron-releases` could somehow be causing #1323.

fix: manually update electron-releases module

---

data/blog/electron-3-0.md

🙅  DO NOT MERGE 🙅 
RFC: please comment with any changes you'd like to see in our preliminary post for the release of `v3.0.0`!
/cc @electron/mergers

feat: add blog post for 3.0.0 release

---

data/blog/electron-3-0.md

fix: update blog post date

---

data/blog/app-feedback-program.md

Oops, wrong date on first merge 🙈

fix: edit AFP blog post date to today's date

---

.gitignore
script/gen-precache.js
scripts/service-worker.tmpl.js

Fixes bad cache causing old versions to appear

fix: handle cache busting of the precache js file

---

data/blog/app-feedback-program.md

Update App Feedback Program sign-up form for v5.0

fix: update AFP sign-up form link

---

styles/_app.scss

|---|---|
| ![before](https://user-images.githubusercontent.com/24681191/50880794-44419580-13e8-11e9-9d37-b7683e1a066d.png) | ![after](https://user-images.githubusercontent.com/24681191/50880804-4b68a380-13e8-11e9-8a97-a807bc5063bb.png) |

feat: truncate long strings on apps page

---

package-lock.json
package.json

chore: bump electron-apps to 1.7275.0

---

package-lock.json
styles/_app.scss

Fixing https://github.com/electron/electronjs.org/pull/1778#issuecomment-452908909
| --- | --- |
| ![before](https://user-images.githubusercontent.com/24681191/50947474-3b63c900-14a7-11e9-8476-23245425494d.png) | ![after](https://user-images.githubusercontent.com/24681191/50947453-1ec79100-14a7-11e9-826a-4bedefce336a.png)

fix: truncating for download block

---

data/locale.yml
styles/_releases.scss
views/releases/index.html

feat: add sidebar on releases page

---

data/blog/window-open-fix.md

blog post for the `window.open()` fix

Window open fix

---

templates/app.html

fix: old path for apps icons in search

---

CONTRIBUTING.md

docs: add notes on deployment and preboot

---

middleware/browserify-opts.js
package-lock.json
test/index.js

test: don't return value in tests

---

data/blog/linux-32bit-support.md

I've promised @nornagon I'd make this clear as soon as one person asks, and a person asked 👯‍♂️

fix: Make the Linux announcement more clear

---

data/blog/filereader-fix.md

cc @electron/wg-security @codebytere

chore: add blog post for filereader vuln

---

data/blog/from-native-to-js.md

fix: blog post year 2018=>2019

---

views/404.html
views/donors.html

Similar to #2317. One more PR with update styles to `@primer/css`.
Updated pages:
- 404
- Donors
- Blog Page and post
How it looks:
| --- | --- |
| ![electronjs org_404](https://user-images.githubusercontent.com/24681191/55023477-8ea8da80-5005-11e9-99f9-80178be3e3f5.png) | ![localhost_5000_404](https://user-images.githubusercontent.com/24681191/55023564-bbf58880-5005-11e9-9021-6c59ca5bdf44.png) |
| --- | --- |
| ![electronjs org_donors](https://user-images.githubusercontent.com/24681191/55023641-ed6e5400-5005-11e9-9d2b-9d955163b82f.png) | ![localhost_5000_donors](https://user-images.githubusercontent.com/24681191/55023716-168ee480-5006-11e9-88d8-2543fce12763.png) |
| --- | --- |
| ![electronjs …

feat: Update more pages to `@primer/css`

---

data/blog/electron-5-0.md

We are in the year 2019.
cc @sofianguy

chore: fix date on 5-0 blog post

---

public/styles/_base.scss
public/styles/_variables.scss

fix: colors fixups

---

data/blog/electron-joins-openjsf.md

docs: Fix double intro

---

data/blog/cadence-pause.md

Address upcoming changes to Electron's Release schedule.
cc @electron/wg-releases

docs: add cadence update post

---

data/locale.yml
public/styles/_base.scss
public/styles/_home.scss
routes/home.js

https://twitter.com/kwuchu/status/1267436741692133376
This PR adds a show of solidarity for our community and Black Lives Matter. As part of this PR, I also added a bit of additional padding on the announcement banner, to draw more attention to the message. Happy to change that back if needed:
Open for discussion about whether we want to keep the website up, or also shut the site down.

In solidarity with our community

---

views/blm.html

Adds Color of Change to the list of recommended orgs for donation.

Add Color of Change to donation page

---

views/blm.html

Changes an incorrect name to a correct name.

fix: use correct name

---

cypress/integration/actions.js
data/locale.yml
routes/home.js
test/index.js

This PR updates Electron's homepage back to our original design, and updates the announcement banner to point to our BLM message.

Chore: Update homepage to original design

---

data/blog/electron-openjs-impact-project.md

This PR adds a new blog post for OpenJS Impact Project announcement.

Chore: Add blog post for OpenJS Impact Project announcement

---

scripts/platform-specific-content.js

👋 Just noticed this while browsing the website.

fix: remove unneeded console.log

---

package-lock.json
package.json

Reverts electron/electronjs.org#4309

chore: revert "build(deps): bump helmet from 3.23.3 to 4.0.0"

---

data/blog/discord-hacktoberfest-2020.md

docs: add blog post for discord + hacktoberfest

---

views/home.hbs

fix: remove semantic <figure> tags from installation instructions

---

data/blog/apple-silicon.md

This is actually 12.2.0, version numbers are complicated 😆

docs: update Xcode requirement for Apple Silicon native modules

---

lib/blog.js
package-lock.json
package.json
routes/blog/index.js
routes/blog/show.js
routes/feed/blog.js
routes/feed/mainFeed.js

The blog was leaking memory because of a race condition with Promises when creating a new `BlogPost`. Because many of the properties relied on the same property, multiple Promises where created to access the same content.

fix: memory leak in blog

---

views/partials/head.hbs

Removing it as we will be using another solution in the future

chore: remove appzi

---

data/blog/electron-12-0.md

cc @sofianguy 
Please add a comment for items you think we should highlight in the blog post!
⚠️ do not merge until the following are completed ⚠️

chore: Electron 12 blog post

---

nodemon.json

Added a minor fix for #5115. 
Maybe @erickzhao can have a look at it :)

fix: Restrict nodemon from restarting server if tests are changed.

---

cypress/integration/actions.js
package.json
script/precompile-assets.js
scripts/search.js
server.js
templates/app.hbs
views/apps/index.hbs
views/apps/show.hbs
views/devtron.hbs
views/fiddle.hbs
views/home.hbs
views/partials/featured_app.hbs
views/partials/footer.hbs
views/partials/head.hbs
views/spectron.hbs
views/userland/devtron.hbs
views/userland/index.hbs
views/userland/spectron.hbs

Adds an extra step to the precompile step to hash all the images so we can use the CDN and change the max-age values in another PR

chore: hash images

---

.github/workflows/test.yml
package-lock.json
package.json

Takes care of missing dependency PRs

Dependency updates

---

package-lock.json
package.json

Did some funky things with link colours that we'll need to fix manually.

fix: revert Primer 16 upgrade

---

.github/dependabot.yml
package-lock.json
package.json

This reverts commit 75e83d2ad82c1edc4da62be75ae5aa253a4cdc06.

chore: Revert "build(deps): bump @primer/css from 15.2.0 to 16.1.2 (#5288)"

---

.github/semantic.yml

Similar to https://github.com/electron/electron/pull/27276

chore: only check semantic PR titles

---

public/styles/_versions.scss

Refs: https://twitter.com/samwightt/status/1405678674024730629

fix: use vendor prefixes for .no-select

---

docs/infrastructure.md

Hello everyone!
In this PR, I just corrected the word `Infrastructure` in the title.

fix: Correction of the word infrastructure

---

data/locale.yml

redirects to our new vanity URL

fix: discord link
