electron/electronjs.org

- .gitignore
- Gruntfile.js
- package.json
You can run `grunt linkChecker` to see any broken links.
We can eventually wire this into CI.
/cc @jlord
> Add link checker grunt task

- _docs/latest/api/browser-window.md
- _docs/latest/api/clipboard.md
- _docs/latest/api/dialog.md
- _docs/latest/api/frameless-window.md
- _docs/latest/api/global-shortcut.md
- _docs/latest/api/ipc-main-process.md
- _docs/latest/api/ipc-renderer.md
- _docs/latest/api/menu-item.md
- _docs/latest/api/menu.md
- _docs/latest/api/remote.md
- _docs/latest/api/synopsis.md
- _docs/latest/api/tray.md
- _docs/latest/api/web-view-tag.md
- _docs/latest/tutorial/application-distribution.md
- _docs/latest/tutorial/quick-start.md
- _docs/v0.27.0/api/browser-window.md
- _docs/v0.27.0/api/clipboard.md
- _docs/v0.27.0/api/dialog.md
- _docs/v0.27.0/api/frameless-window.md
- _docs/v0.27.0/api/global-shortcut.md
- _docs/v0.27.0/api/ipc-main-process.md
- _docs/v0.27.0/api/ipc-renderer.md
- _docs/v0.27.0/api/menu-item.md
- _docs/v0.27.0/api/menu.md
- _docs/v0.27.0/api/remote.md
- _docs/v0.27.0/api/synopsis.md
- _docs/v0.27.0/api/tray.md
- _docs/v0.27.0/api/web-view-tag.md
- _docs/v0.27.0/tutorial/application-distribution.md
- _docs/v0.27.0/tutorial/quick-start.md
This updates the `v0.27.0` and `latest` doc versions to include the updated internal links which are now absolute and work from wherever :sparkles:
> Update v0.27.0 and latest

- lib/doc-links.js
- lib/fetch-docs.js
The script to fetch docs assumed that the OS path separator is always a forward slash (`/`) and while that works for most *nix-based systems, it was failing on Windows. This PR fixes that by using [`path.sep`](https://nodejs.org/api/path.html#path_path_sep) from Node wherever possible.
> Fix doc script assumptions about OS path separator

- README.md
- _layouts/releases.html
This adds instructions for updating the releases info to the readme and on the releases page it now links to view all the releases (on GitHub) since just the latest are shown.
> Releases instructions and link to view all 

- index.html
When I was first getting started with Electron, I didn't know there was a Quick Start guide and that that was where I should've started. This PR links to the Quick Start guide in the Getting Started section at the bottom of the home page, which will hopefully help to make it a bit more discoverable.
/cc @jlord
> Make Quick Start guide more discoverable

- index.html
This incorporates https://github.com/atom/electron.atom.io/pull/66 which points to the Quick Start Guide and adds a reference to this site's documentation (instead linking to repository) and to @sindresorhus's `awesome-electron` list (linked to by the `atom/electron` readme, too).
cc @mnquintana
> Update the Get Started Section

- _includes/anchor_links.html
- _layouts/default.html
- css/main.css
This PR adds the scripts and liquid templates that Jekyll needs to turn headers into _headers with permalinks_. [Info on how here](https://george-hawkins.github.io/basic-gfm-jekyll/redcarpet-extensions.html#hover-anchors).
I'm not :100: on having hidden link icons that you have to hover to see so if no one else hates them I've got them to the right of headers like so:
Closes https://github.com/atom/electron.atom.io/issues/34
> Add Permalinks to Headers

- css/main.css
Closes #71 
Code overflows background area.
Changes: 
Adds horizontal scrolling to code tag to prevent text from overflowing background area.
> Adds horizontal scrolling to code tag

- _includes/head.html
- _layouts/docs.html
- css/main.css
:construction: 
This PR updates some CSS styles on the documentation pages to improve their layout. 
The documentation changes are currently being made in `atom/electron` which will then be updated here at the next minor version release (once those changes are merged). 
In the meantime, improvements include:
- Colored events and method headers
- Specific callouts to platforms
---
It's hard to actually see these changes without the updated docs so I've just been copying and pasting them into here to test. 
cc @simurai :eyes: and :bulb:
> [WIP] Docs Style Updates

- css/main.css
The correct CSS :sparkles: :tophat: @muan.
This also fixes it in Events which previously weren't getting the style at all. 
Fixes #84
> Display Platform Labels Correctly

- index.html
The spaces that followed the links triggered an underline after each
image when hovering the images.
I removed the spaces but this messes up the indentation used there. This could also be fixed by adding a class to the div they're all inside and writing a specific CSS rule that removes text decoration for links inside that.
> Removed space after links

- _config.yml
This adds some excludes to Jekyll's config file to speed up the build process, especially `node_modules`, which doesn't appear to be used in the built site (Jekyll won't watch for changes in these folders or try to copy the files over to the site's output directory).
Testing locally, the build time went from about a minute to about 15 seconds.
/cc @jlord
> Exclude files not needed from the build process

- index.html
This updates the Get Started section to point people to the Quick Start app:
Before:
After:
> Update Get Started with Quick Start Repository

- _config.yml
- css/main.css
- index.html
- package.json
- script/versions
This adds a script and small section to the front page to display what the latest version of Electron is and what versions of Node, Chromium and V8 it's using :computer: 
Currently it'll just be manually run when we do a release (or maybe just `minor` releases) but :soon: I'll put this and the docs and releases data into a single thing that's run after a hook :fishing_pole_and_fish:
> Add Electron, Node, Chromium, V8 Versions to Home Page

- README.md
- package.json
- script/docs
This adds a command for updating at once all the things that need to be updated when a minor version of Electron is released. 
- Add a bit of args logic so that I can reverse order of option so that I can make npm scripts work with an argument in the way I need it to
- Update docs
- Add npm scripts
Here's what it'll look like when it runs:
```bash
npm run lastest -- v0.36.0
> electron.atom.io@1.0.0 lastest /Users/jlord/github/electron.atom.io
> npm run rels-vers && npm run docs "v0.36.0"
> electron.atom.io@1.0.0 rels-vers /Users/jlord/github/electron.atom.io
> script/releases && script/versions
> electron.atom.io@1.0.0 docs /Users/jlord/github/electron.atom.io
> script/docs --latest "v0.36.0"
Downloading electron.tar.gz
[=================================================>] 100.0% (1.82 …
```
> Create Update All Script

- _docs/latest/tutorial/application-distribution.md
- _docs/v0.24.0/tutorial/application-distribution.md
- _docs/v0.25.0/tutorial/application-distribution.md
- _docs/v0.26.0/tutorial/application-distribution.md
- _docs/v0.27.0/tutorial/application-distribution.md
- _docs/v0.28.0/tutorial/application-distribution.md
- _docs/v0.29.0/tutorial/application-distribution.md
- _docs/v0.30.0/tutorial/application-distribution.md
- _docs/v0.31.0/tutorial/application-distribution-es.md
- _docs/v0.31.0/tutorial/application-distribution.md
- _docs/v0.32.0/tutorial/application-distribution.md
- _docs/v0.33.0/tutorial/application-distribution.md
- _docs/v0.34.0/tutorial/application-distribution.md
- _docs/v0.35.0/tutorial/application-distribution.md
- _docs/v0.36.0/tutorial/application-distribution.md
- _docs/v0.36.3/tutorial/application-distribution.md
- _docs/v0.36.4/tutorial/application-distribution.md
- _docs/v0.36.5/tutorial/application-distribution.md
- Apparently ResEdit now comes bundled with undesirable executables, so let's remove the recommendation.
- Closes atom/electron#4357
> Removed Trojan Link

- Gemfile
- _config.yml
Switching our highlighter and markdown parser to work with changes in Jekyll 3.0 :memo: 
Closes https://github.com/atom/electron.atom.io/issues/142
> Use Kramdown + Rouge

- lib/doc-links.js
- lib/fetch-docs.js
- spec/fixtures/doc-with-internal-links.md
- spec/fixtures/test-set-docs/tutorial/quick-start.md
- spec/link-fixing.js
All of the Electron documentation hosted in the repository on github.com is written in markdown and github.com handles any relative links to work correctly on the site.
We use the same docs here on this site so we need to parse for any links and make them work here, too. This pull request updates the parsing so that two forms of markdown links are acceptable. 
- Traditional: (in the body) `[i am a link](github.com)`
- Footer: (in the body) `[i am a link][i-am-link]` (in the footer) `[i-am-link]: https://github.com`
Specs are updated as well :pizza: 
cc @kevinsawicki :pear:
> Parse Documentation for Footer Links

- _layouts/docs.html
http://electron.atom.io/docs/all is a thing! This adds a link to it in the docs footer:
The icon layout needs a little love, but I'd rather :ship: and save that fix for another PR.
> add link to /docs/all

- index.html
There is no hostname `www.lighttable.com`, but `lighttable.com` works:
```
Z:\>ping www.lighttable.com
Ping request could not find host www.lighttable.com. Please check the name and try again.
Z:\>ping lighttable.com
Pinging lighttable.com [192.30.252.153] with 32 bytes of data:
Reply from 192.30.252.153: bytes=32 time=81ms TTL=52
Reply from 192.30.252.153: bytes=32 time=80ms TTL=52
Reply from 192.30.252.153: bytes=32 time=80ms TTL=52
Reply from 192.30.252.153: bytes=32 time=80ms TTL=52
Ping statistics for 192.30.252.153:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
Minimum = 80ms, Maximum = 81ms, Average = 80ms
```
> LitghtTable link fix

- _config.yml
- _data/releases.json
- _layouts/releases.html
- _pages/index.html
- _pages/releases.md
- lib/fetch-docs.js
- script/releases
- spec/documentation-spec.js
- spec/fixtures/test_config.yml
Noticed on the homepage that the Chrome, V8, and Node versions don't have a `v` prefix but the Electron version did.
This pull request removes that and so Electron releases will show with labels like `1.1.0` instead of `v1.1.0`.
/cc @jlord @simurai
> Drop the leading v from Electron version

- _data/processes.yml
- BrowserWindow is not listed on http://electron.atom.io/docs/ .
- http://electron.atom.io/docs/api/browser-window/ does not show its category.
> Fix typo in _data/processes.yml

- lib/fetch-docs.js
We create redirect urls for each page in the docs because we've changed what docs are on the site and where they are. This way old URLs that persist in Google searches will still take the user to the correct spot.
We were generating this URL based on all versions of Electron listed in the `_config` but the old urls only exist for versions prior to `1.0`. 
This PR updates the script so that we're only creating redirect URLs for versions prior to `1.0`.
You can see the result of this change in the new docs PR #302.
/cc @kevinsawicki
> Only create redirect URLs for older versions

- _data/meetups.yml
- _pages/community.html
This adds a section at the bottom of the page to list Electron meetups.
The data comes from a new `_data/meetups.yml` file that people can henceforth add there meet up to! 
---
---
/cc @kevinsawicki 
Closes #304
> Add meetups section to community page

- _pages/community.html
This PR updates links on the community page so that external links open in a new tab and that the `meetups.yml` link opens directly to the edit view.
> Update links on community page

- CONTRIBUTING.md
- README.md
This updates the `README.md` to better reflect site documentation changes since `1.0`. It also adds links to the main things people may need the repository for: adding an app or meetup to the site.
It also adds information on adding a meet up to the site in `CONTRIBUTING.md`.
> Update readme and contributing docs

- _pages/404.html
- _pages/api.md
- _pages/apps.html
- _pages/blog.html
- _pages/community.html
- _pages/development.md
- _pages/docs.html
- _pages/guides.md
- _pages/releases.md
The new Jekyll plugins at an `- Electron` suffix for SEO reasons so this pull request removes the redundant prefix.
Follow on to #248
> Drop Electron prefix from page titles

- CONTRIBUTING.md
This PR makes an update to the app submission guidelines to specify pointing to a website or repository with a `README` . 
This is to insure we don't link directly to downloads or pages with just downloads in order for users to have a bit more information before they decide to install. 
This also points people to [GitHub Pages](pages.github.com) as an option for a free website 💻
> Revise app submission re: websites

- spec/featured-spec.js
Sometimes pull requests add `featuredOnHomepage: true` in their pull requests and since we aren't adding new ones at this time, this pull request adds a spec verifying exactly 16 are featured so we know the right amount appear on http://electron.atom.io/
/cc @jlord
> Add spec for 16 featured apps

- _docs/faq/electron-faq.md
- lib/fetch-docs.js
In the Electron docs the FAQ page is located at `/docs/faq/electron-faq.md`. To make the url nice and neat on the site we were adding a permalink to FAQ page of `/docs/faq`. 
This was breaking links to the FAQ from the original docs that use the path as it is in the repository. To handle this and keep our neat and short url I've added another redirect url for the page from `/docs/faq/electron-faq/`.
This fixes an issue opened in https://github.com/electron/electron/pull/5899.
> Add redirect URL to FAQ

- _includes/featured_app.html
- _includes/featured_open_source_apps.html
This adds `| escape` to the places where we are using `app.description` which may contain characters that break how the text is parsed. 
cc @zeke @as-cii
Closes #342
> Escape app descriptions

- _layouts/docs.html
I don't think we surface anywhere on the site the fact that there are some doc translations. Those translations aren't as up to date as the ones on the site but I thought it was maybe still helpful to expose? cc @zeke
> Add link to doc translations

- _sass/_docs.scss
The docs now contain a Markdown table via http://electron.atom.io/docs/api/app-locales/
This pull request styles all `<table>` elements under a `.docs` class so that they get a nicer styling that mirrors the other pages.
| --- | --- |
|  <img width="831" alt="screen shot 2016-07-08 at 11 55 06 am" src="https://cloud.githubusercontent.com/assets/671378/16698488/54e2cd7a-4503-11e6-958c-fba4eac94484.png"> |  <img width="816" alt="screen shot 2016-07-08 at 11 54 39 am" src="https://cloud.githubusercontent.com/assets/671378/16698482/4cadb2aa-4503-11e6-8b91-309de2cee39e.png"> |
> Style all table elements that appear in docs

- lib/fetch-docs.js
This adds a special redirect for the locales doc page which has been renamed and therefore will have a new path when the next version of Electron ships.
Was thinking that we needed to wait but actually this can be merged now and won't effect anything.
Closes https://github.com/electron/electron.atom.io/issues/374
> Add redirect for old locales doc path

- lib/fetch-docs.js
When the next version of docs ships the FAQ will live at this location so we don't need to use the permalink anymore ✨ 
cc @zeke I think this is all we need to change to prep for that update?
> Remove permalink for FAQ

- _posts/2015-04-23-electron.md
Saw the old email address in the old post when I was linking it for a Discuss member. I figured updating it would be good.
> Update email address in Electron announcement post

- _docs/faq.md
- lib/fetch-docs.js
We moved the FAQ to the root which messed up the doc generator because it previously didn't expect anything in the root. 
This PR just explicitly looks for the FAQ. If our structure gets more complex in the future we can rethink this bit of logic. 
@zeke this is to merge into your https://github.com/electron/electron.atom.io/pull/378
> Fix FAQ breadcrumb

- _sass/_docs.scss
These styles regressed when we updated the styleguide and docs to use H4-level headings for things like Events and Instance Methods.
👀  @kevinsawicki
> apply OS label style to H4 in addition to H3

- _data/apps.yml
- _drafts/roundup.md
To make creating the monthly roundups easier I had this idea—
(Note: For this month’s post I went through the PRs, labeled the ones that were app additions thinking doing a search through that list would be the easiest way to see what was added when.)
- When a fresh :tulip: roundup is cut the author should go into `_data/apps.yml` and add a header for the **new** month :calendar: 
- Then create the post based on everything in the list up until the **previous** month header. 
This will be much easier than going back and forth copy :spaghetti:  from PRs.
> Helpers for creating monthly roundups

- _sass/_blog.scss
When previewing #410 I noticed that links that were wrapping `<code>` tags didn't get any new style so it was hard to tell they were links at all. This gives them the same colors as text links and you can now 👀 them. 
|---|---|
| ![img](https://cloud.githubusercontent.com/assets/1305617/17490136/3c59cfea-5d56-11e6-8ff3-e7efaa191459.png) | ![img2](https://cloud.githubusercontent.com/assets/1305617/17490133/36943712-5d56-11e6-89df-ca9ef45c2857.png) |
---
> Add color to links within <code>

- _layouts/docs.html
- _sass/_docs.scss
Platform labels were not getting styled anywhere other than in method/event headers. There are platform labels, however, in the lists of arguments for methods and those need to be styled.
There _shouldn't_ be anything else we're using `em` for in a list in the docs (I think??) so what I have now may be fine: `.docs li em` but I'd like @simurai's thoughts. Should it be more specific? 
🔗 [to live doc](http://localhost:4000/docs/api/auto-updater/#autoupdatersetfeedurlurl-requestheaders)
Fixes #419 
Fixes #421
> Style platform labels in lists

- _layouts/docs.html
This adds some JS to remove the incorrectly applied syntax highlighting style added by the default highlighter in Jekyll. 
**Before**
**After**
Fixes #402
> Remove incorrect string template styles

- _layouts/releases.html
This updates a section on the releases page to now use `electron` as the module name rather than `electron-prebuilt`. 
[Blog post on the change](http://electron.atom.io/blog/2016/08/16/npm-install-electron) 📝
> Update electron-prebuilt → electron on releases page

- _data/apps.yml
A quick fix suggested by @amitmerchant1990 to add the website attribute as at the moment the link doesn't go anywhere apart from the current apps page.
> Added website attribute to Ionic Creator & TwitchAlerts

- _includes/featured_app.html
- _includes/featured_open_source_apps.html
As @amitmerchant1990 pointed out https://github.com/electron/electron.atom.io/pull/424#issuecomment-240324301, not all apps provided a `website` so the linked image just refreshed the page.
This PR updates the template to use the `repository` URL if no `website` is provided. 
Thanks @muan for this ProTip™ ⭐ `{{ app.website | default: app.repository }}`
> On apps page use repository URL if there is no website

- _pages/api.md
- _sass/_basecoat-tables.scss
This adds the process/s name in the table of Electron APIs at [electron.atom.io/docs/api](http://electron.atom.io/docs/api).
I added a class to fit it all in there but don't know if it should be done in a different way so pinging @simurai for thoughts ✨ 
| --- | --- | 
|<img width="911" alt="screen shot 2016-08-19 at 2 07 24 pm" src="https://cloud.githubusercontent.com/assets/1305617/17824354/4e28d734-6616-11e6-8fa1-2e804024bd4a.png">|<img width="1062" alt="screen shot 2016-08-18 at 1 33 20 pm" src="https://cloud.githubusercontent.com/assets/1305617/17824338/2f3bc85e-6616-11e6-9cc7-3f7aa111cc7f.png">|
There is an After-After also... The "Process" and "Processes" text looks repetitive so I took it out but that meant needing to add table headers. What's your preference …
> Show process in API Reference table

- lib/roundup-helper.js
This adds a little helper for generating markdown table rows based on apps in `_data/apps.yml` so that there is much less copypasta needed to do a roundup post. Automation! 💥 
This will mostly be used by myself and/or Electron team when working on these types of posts ✏️ 
[Example roundup post](http://electron.atom.io/blog/2016/09/06/august-2016-roundup)
cc @zeke @kevinsawicki
> Add roundup blog post helper

- _includes/head.html
- _layouts/docs.html
- _pages/index.html
- _sass/_highlight.scss
- js/index.js
- js/update-download-link.js
This PR shuffles some javascript around so that the syntax-highlighting fixes are applied on all pages instead of just the docs pages. It also disables/removes some styles that make javascript look weird:
Before | After
--- | ---
#491 includes some affected snippets, so it would be nice to land this first.
👀 @jlord @kevinsawicki
> Syntax highlighting fixes

- _posts/2016-09-27-api-docs-json-schema.md
The previous link led to a 404 page on npmjs. 😄
> fix broken link to npmjs package

- _data/apps.yml
- Pixate is shutting down and is no longer available
- antSword points to an empty git repository
> Remove two defunct apps from app list

- _pages/api.md
- lib/doc-links.js
- lib/fetch-docs.js
Fixes #509 
This updates the markdown parser to rewrite links to the new files in `/docs/api/structures`.
cc @MarshallOfSound
> Structures

- _data/apps.yml
- spec/featured-spec.js
This PR adds four more featured apps to the homepage:
- https://getkap.co @matheuss @CodeTheory
- https://zeit.co/app @rauchg @leo
- https://beakerbrowser.com @pfrazee
- http://www.svgs.us @stonebranch
> feature four more apps on homepage

- _docs/api/net.md
- lib/doc-links.js
I pinged the GitHub Pages team about this one. @parkr points out that there are some deficiencies in the [kramdown](https://github.com/gettalong) markdown parser used by Jekyll:
> It uses regular expressions to match things. So if you have `|` then 10 lines later a `|`, the content in between may be considered a table.
It would be nice to land a fix for this in kramdown itself, but here is an interim fix. The line-by-line technique is used to match a specific pattern and avoid encoding pipes elsewhere in our markdown files.
cc @gettalong, maintainer of kramdown
cc @aliib, who reported the issue
cc @kevinsawicki, pull-request-reviewer extraordinaire
Fixes #556
> Encode pipes so they don't become tables

- _posts/2016-12-09-certificate-transparency-fix.md
Details an important fix in Electron 1.4.2 where certificates incorrectly are rejected 10 weeks after the build date of Electron's libchromiumcontent library.
> Add certificate transparency post

- script/release
This fixes a bug in the release process so that git config doesn't fail.
> run git config after cloning

- package.json
This will prevent any regressions from new reports that don't yet have a companion template in the website repo.
> lock the github-userland-reports dep

- _docs/api/browser-window.md
- _docs/api/clipboard.md
- _docs/api/crash-reporter.md
- _docs/api/dialog.md
- _docs/api/native-image.md
- _docs/api/process.md
- _docs/api/screen.md
- _docs/api/session.md
- _docs/api/shell.md
- _docs/api/web-contents.md
- _docs/api/web-view-tag.md
- lib/doc-links.js
- lib/fetch-docs.js
- spec/link-fixing.js
Regex was using `.+` which would go all the way to the end of the last `)` found, now switched to use `[^)]+` instead so it stops at the first `)`.
This pull request also includes a rebuild of the docs to make sure only the broken links gets fixed.
Closes #567
> Fix multiple links on a line

- _config.yml
- _layouts/docs.html
- _pages/docs.html
- _pages/index.html
- _posts/2015-06-04-electron-doumentation.md
There were some leftover spots in the templates that were reading a `latest_version` value from the Jekyll config. Nowadays, the config file is just for configuration. All the ever-changing Electron-related data lives in the `_data` directory.
> read latest version from data, not config

- _includes/userland_report.html
There was a point at which [repos-using-electron](https://github.com/electron/repos-using-electron) was omitting [all those `foo_bar_baz_url` properties](https://api.github.com/repos/electron/electron) that are returned by the GitHub API, but now those properties (though largely redundant) are retained, because having them doesn't really hurt anything.
So... some repos are missing `htmlUrl`. This PR works around that by constructing the repo URL with `fullName`, a property which every repo is [guaranteed to have](https://github.com/electron/repos-using-electron/blob/3551ef4210f052d59dd65f0885e079fe564a9edc/test/index.js#L28-L31).
Also opened https://github.com/electron/repos-using-electron/issues/13 as a reminder to eventually fix the data at the source.
Thanks to @pfrazee for reporting.
> fix userland repo links

- _docs/tutorial/about.md
Fixing a 404 on the main about page linked to an incorrect path for the quick start page
> Fixing broken link in about tutorial page

- _docs/api/browser-window.md
- _docs/api/client-request.md
- _docs/api/menu-item.md
- _docs/api/net.md
- _docs/api/session.md
- _docs/api/tray.md
- _docs/api/web-contents.md
- _docs/api/web-view-tag.md
- lib/doc.js
- test.js
Fixes #556 (again). This regressed because it [didn't have a test](https://github.com/electron/electron.atom.io/commit/6c4d991485a82c7b5ba09d4869ff7a0b9f4e6054), and fell through the cracks when #630 landed.
👁 @kevinsawicki
> Encode pipes

- _includes/header.html
This PR replaces the link to https://discuss.atom.io/c/electron with a link to http://electron.atom.io/contact/ which lists our GitHub, Twitter, Slack, Discourse, and email address.
Eventually it would be nice to have a short blurb outlining the purpose of each of those accounts,  but this is at least a start to help people more easily find the available channels for communicating with us and the community.
> link to contact page from header

- CONTRIBUTING.md
- README.md
@felixrieseberg recently asked what "frameworks" we are using on the site.
This PR is an attempt to answer that question. Specifically: https://github.com/electron/electron.atom.io/blob/5ed85c4fb606aeae73d03a194e3d6b336776905d/CONTRIBUTING.md#how-the-site-is-built
I also moved most of the contributing info to `CONTRIBUTING.md` and pared down the README to include a few links to address the most common contribution cases:
1. adding apps
1. adding meetups
1. updating docs
> Improve readme and contributing

- _data/meetups.yml
The London Meetups group seems to have disappeared. Probably ought to be removed from the website pending confirmation it exists.
> Removing London from meetups list

- test.js
https://github.com/electron/electron/pull/7878/files rewrites the URL of the `Main Process` and `Renderer Process` links in each API doc.  Once that lands in a release, a few tests will start failing here.
This PR exists in anticipation of that future...
> fix link tests to account for electron docs changes

- _sass/_home.scss
- _sass/_userland.scss
This is a small follow up to #654.
After typing a search query, some people might just use `tab` to move down the list and then hit `enter`. This PR makes hover and focus styles the same. Border got added to make it a bit stronger.
👀  [Preview](http://simurai.com/electron.atom.io/apps/)
> Add focus styles to app list

- script/releases
Looks like http://electron.atom.io/ is still showing 1.4.14 even though 1.4.15 is out.
I ran `./script/release` locally and the specs were failing on 1.4.15 because of the hyperlink spec, looks like some releases use `\r\n` and others `\n`.
This pull request just use the `$` anchor so both are handled.
> Use EOL anchor when replacing links

- .gitignore
- package.json
- script/notify
This PR replaces https://github.com/electron/electron.atom.io/pull/670, which I wasn't really very happy with. It was nice to experiment with `shelljs`, and work towards a build script that would work on Windows, but the code ended up being harder to read/write/understand because of the abstraction of JavaScript doing shell scripting... 🤔 
The new approach in this PR is simple:
- The [existing release script](https://github.com/electron/electron.atom.io/blob/60aedf6237a5b91b1f8e793155c295c7c9237670/script/release) remains untouched; it's a simple shell script.
- The `npm run release` command pipes STDOUT and STDERR to a new `notify` script (as well as the screen)
- The `notify` script collects its STDIN, then sends a Slack notification to the new `#website` channel if the input contains …
> Release Notifications, Take 2

- package.json
There's now a bot that periodically [adds metadata](https://github.com/electron/electron-apps/pull/89) to the `electron-apps` repo and publishes it to npm. The bot runs a build script that generates artifacts that are gitignored, like resized icons. This PR updates the website to use that new package instead of the master branch of the `electron-apps` repo.
> Get `electron-apps` from npm

- script/releases
This updates the build script to collect metadata for more than 30 releases, and as many as 100.
> include up to 100 releases, not just 30

- script/notify
> wrap slack release failure notifications in backticks so they collapse

- lib/doc.js
I missed an important spot when implementing https://github.com/electron/electron.atom.io/pull/673 -- this is a fix for that.
> use highest stable version when building docs

- _sass/_home.scss
In #705 is mentioned a small bug related to the app icon size on hover, on narrow screens.
https://github.com/electron/electron.atom.io/issues/705#issuecomment-285457761
This fixes it by not allowing the app icon to scale down anymore.
> re #705: Prevent app icon from scaling down when screen width is small.

- _data/versions.json
- script/versions
I set up the GitHub releases data to be sorted with highest version first, but forgot to do it for the supplementary v8/node/chromium version data that we collect from https://atom.io/download/electron/index.json
This PR fixes that.
> sort versions data from S3 (v8, chromium, node)

- _pages/docs-versions.md
Fixes the issues raised in: https://twitter.com/amsoell/status/842674759053852676 that links to old documentation didn't work
> Fix the links to old docs

- _docs/api/browser-window.md
- _docs/api/client-request.md
- _docs/api/menu-item.md
- _docs/api/session.md
- _docs/glossary.md
- lib/doc.js
- test.js
Fragments links are currently being converted to be rooted at the wrong page, this pull request changes the link converter to ignore them.
Refs https://github.com/electron/electron/pull/9065#issuecomment-296514242
> Don't convert fragment links

- lib/doc.js
- package.json
A followup to https://github.com/electron/electron.atom.io/pull/725 that updates the `href-type` package with support for detecting fragment URLs like `#about-us`
> update href-types package for fragment link detection

- package.json
- script/notify
Problem: Slack is getting spammed with stack traces that most people don't want to see.
Solution: Update the deployment process to post failures to a gist, then notify in slack with the gist URL.
> post deployment errors to a gist

- _data/locale.yml
- _pages/index.html
Was browsing the site when I noticed the Quick Start title wasn't loading properly. Noticed it was missing the opening brace so I fixed it!
> Fix missing open bracket in quick start title

- lib/browsersync.js
Editing files like `server.js` was causing browsersync to refresh, and because I am a convulsive file-saver, the browser refresh would sometimes occur when `server.js` contained malformed code. As such, browsersync would sometimes refresh at a time when the server would crash, occasionally  requiring a manual browser refresh.
This change is an attempt to solve that issue by preventing browsersync from refreshing when server-side JS files are being edited.
> tweak browserync watched files

- data/locale.yml
- server.js
- views/contact.html
One of my goals this week is to chip away at the jekyll-to-node migration: #758
This little PR ports the `/contact` page from Jekyll style to Express style, and paves the way for injecting pages with localized `<meta>` data like  `title` and `description`
> migrate contact page

- app.json
Not actually needed for this branch, but Heroku requires it for Review Apps to work.
> add app.json for heroku

- package-lock.json
- package.json
- views/apps/show.html
Update app pages to use accessible colors for links and buttons. Colors are derived from the app icon and are guaranteed to be [accessible](https://github.com/zeke/make-color-accessible).
> use derived colors on app pages

- lib/apps.js
- package-lock.json
- package.json
- routes/apps/index.js
- scripts/update-app-download-links.js
- server.js
- test/index.js
- views/apps/index.html
- views/community.html
Some people visit the site periodically looking for the latest app additions. This way the newest stuff is always on top. Eventually we should enable sorting by other things: name, popularity, etc. But in the mean time this PR makes the behavior consistent with the existing site.
> Sort apps by date

- middleware/browsersync.js
- styles/_base.scss
- styles/_basecoat-code.scss
- styles/hljs/github.css
- styles/hljs/overrides.scss
- styles/index.scss
- views/layouts/docs.html
Jekyll has its own [set of tools](https://jekyllrb.com/docs/templates/#code-snippet-highlighting) that do syntax highlighting for code snippets. We're now using [remark](http://ghub.io/remark) to parse markdown and the [remark-highlight.js](http://ghub.io/remark-highlight.js) plugin for code snippets. They use different approaches to structuring the code, and different CSS classes for the various code components like comments, keywords, builtins, etc.
I pulled in the GitHub Highlight.js theme from here: https://github.com/isagalaev/highlight.js/blob/master/src/styles/github.css, then added a little bit of styling to get it mostly consistent with what we had before.
Before:
After:
cc @simurai @donokuda
> Syntax highlighting

- data/locale.yml
- views/docs/index.html
- views/partials/docs_footer.html
This PR moves more strings into `locale.yml` so they can be translated.
> localize docs footer

- .travis.yml
- data/locale.yml
- middleware/context-builder.js
- package.json
- server.js
- styles/_basecoat-tables.scss
- styles/_nav.scss
- views/partials/footer.html
- views/partials/header.html
This PR adds the user's currently selected language to the right edge of the header nav.
Here it is in English, which everyone defaults to, regardless of their browser's `accept-language` header:
And in Japanese:
And in Chinese on mobile:
Clicking on the language leads to `/languages` where another language can be chosen. The choice persists in an everlasting cookie. 🍪 
cc @donokuda @groundwater @vanessayuenn
> Locale Nav

- package-lock.json
- package.json
This problem popped up again after Greenkeeper updated primer-breadcrumb in #805.
https://github.com/electron/electron.atom.io/pull/806
https://github.com/primer/primer-css/issues/317
> lock primer-breadcrumb at 1.0.2

- data/meetups.json
fix address to "https://electron-kr.github.io/electron-kr"
I changed it to '@ragingwind' request.
You can refer to #11078 in electron/electron
> Fix Address of Korea Community

- data/locale.yml
- middleware/context-builder.js
- routes/_404.js
- routes/apps/index.js
- server.js
- test/index.js
- views/404.html
Created a 404 handler instead of just rendering the 404 page, so that all `req.context` is available to render the nav etc. Localized the 404 page and made sure that all missing routes are reaching the new default handler. Added a link to open an issue on GitHub that includes the 404-ing path.
> Better 404

- data/locale.yml
I looked elsewhere and could not find a mention of twitter_username, but there are a couple of direct links to twitter.com/electronjs (just search this repo for "twitter"), so I opted to fix it that way (as the other links in this section are direct links too)
> Help section now links to correct twitter account

- styles/_app.scss
- views/apps/index.html
This PR hides app categories on mobile, but leaves filter and moves it above the app list. 
/cc @zeke
> Hide app categories on mobile

- server.js
- test/index.js
I keep typing electron.atom.io/issues into my browser address bar and ending up at a 404 page. This change will solve that for me by redirecting to the GitHub repo's issue pages.
> redirect issues urls to github

- views/community.html
Now that master is the default branch, we can deep link to the right file for editing meetups.
> enable community notice

- CONTRIBUTING.md
- data/blog/accessibility-tools.md
- data/blog/api-docs-json-schema.md
- data/blog/august-2016-roundup.md
- data/blog/chromium-rce-vulnerability.md
- data/blog/electron-1-0.md
- data/blog/electron-doumentation.md
- data/blog/electron-internals-using-node-as-a-library.md
- data/blog/electron-internals-weak-references.md
- data/blog/electron-updates-mac-app-store-and-windows-auto-updater.md
- data/blog/electron.md
- data/blog/jully-2016-roundup.md
- data/blog/july-2016-roundup.md
- data/blog/kap.md
- data/blog/latest-v8-chromium-features.md
- data/blog/new-website.md
- data/blog/september-2016-roundup.md
- data/blog/simple-samples.md
- data/blog/typescript.md
- data/blog/userland.md
- data/blog/voltra.md
- data/blog/webtorrent.md
- data/locale.yml
- package.json
- script/release
- scripts/platform-specific-content.js
- server.js
- test/index.js
- views/404.html
- views/home.html
This PR updates a bunch of references to the old domain.
cc @codebytere
> electron.atom.io → electronjs.org

- data/locale.yml
- package.json
- test/localization.js
- views/home.html
This PR adds some test to verify that all references like `{{localized.foo.bar}}` are defined in `data/locale.yml`, and conversely that all strings defined in the locale file are used by the views.
cc @vanessayuenn
> Test locale strings

- server.js
- test/index.js
Visit https://electronjs.org/pulls and you'll be redirected to https://github.com/electron/electronjs.org/pulls.
> convenience url for pull requests

- data/locale.yml
I noticed that some of the documentation pages for electronjs.org were missing some metadata and showing `undefined` in tabs. I've added to `data/locale.yaml` to fix it
Before:
```
<meta property="og:type" content="website" />
<title>undefined | Electron</title>
<meta property="og:title" content="undefined | Electron" />
<meta name="twitter:title" value="undefined | Electron" />
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@ElectronJS" />
```
After:
```
<meta property="og:type" content="website" />
<title>Tutorial | Electron</title>
<meta property="og:title" content="Tutorial | Electron" />
<meta name="twitter:title" value="Tutorial | Electron" />
<meta property="og:description" content="Guides and tutorials for the latest Electron release" />
<meta …
```
> [SEO] Add missing metadata for documentation pages

- views/apps/show.html
Currently if you copy paste a one liner from the site into terminal it will copy a newline char as well, this will cause the one liner to automatically execute.  My terminal won't auto exec but it does throw warnings my way whenever it prevents something auto executing (how I noticed this) 😄
> Don't auto execute shell one liners

- package-lock.json
- package.json
- server.js
- test/index.js
I tried running lighthouse against the website, and it recommends gzipping the responses
Implemented something, as recommended by [express](https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression). Alternatively they recommend using a reverse proxy.
> gzip-encode response

- package.json
Locking the version string will cause @greenkeeper to open PRs for each new version of `electron-apps`
See https://github.com/greenkeeperio/greenkeeper/issues/554#issuecomment-346984561
> pin electron-apps version

- test/index.js
https://twitter.com/stevesy_mke/status/935521200217968640
Not actually sure how this was happening, as we already have a test that checks the title on the /apps page. In any case a re-deploy solved it and this extra test will hopefully give us a little more protection for further regressions.
> test for title on homepage

- package.json
- routes/languages/stats.js
- routes/languages/status.js
- server.js
- test/index.js
This PR will allow us to store our Crowdin API Key safely in Heroku's env, so contributors to electron-i18n will be able to fetch stats data as part of its build process, without needing to know any secrets.
> proxy crowdin stats

- middleware/blog.js
> Fix missing texts at 404 pages with path: /blog/*

- data/blog/beaker-browser.md
- data/blog/dat.md
- data/blog/ghost.md
- data/blog/jasper.md
- data/blog/kap.md
- data/blog/voltra.md
- data/blog/webtorrent.md
- data/blog/wordpress.md
- styles/_blog.scss
- views/partials/blog_byline.html
- views/posts/index.html
- views/posts/show.html
Fixes #955 
Fixes #707 
This PR updates the blog index and blog pages to display all authors for a post, preserving the singular name `author` for compatibility with the [feed](https://ghub.io/feed) module.
cc @pierreneter
> fix blog bylines

- package.json
Reverts electron/electronjs.org#1019
The upgrade to primer-breadcrumb@1.5.1 seems to have caused the stylesheet to not build properly. Reverting for now.
cc: @zeke 
```
[sass]  error: Undefined variable: "$em-spacer-5".
in /Users/vanessayuenn/Projects/electronjs.org/node_modules/primer-breadcrumb/lib/breadcrumb.scss:8:20
Error: Undefined variable: "$em-spacer-5".
at options.error (/Users/vanessayuenn/Projects/electronjs.org/node_modules/node-sass/lib/index.js:291:26)
```
> Revert "Update primer-breadcrumb to the latest version 🚀"

- middleware/context-builder.js
- test/index.js
This PR allows a `?language=` query param to be added to any URL to view that URL in the target language. This does not have an effect on the visitor's language settings (or lack thereof). In other words, if my language is English and I view `/docs/api/app?language=fr-FR`, I will only see that one page in French. If I click any links or remove the query param from the URL, content will still be displayed in English.
> Support a new `language` query param

- data/blog/protocol-handler-fix.md
This is a cosmetic change that adds an `---` (HR tag) to prevent this entire post from being displayed on the blog index.
> excerptize protocol handler post intro

- middleware/sass.js
- package-lock.json
- package.json
- styles/index.scss
There were a few things I noticed and fixed.
When upgrading `primer-breadcrumbs` before. The build was failing because you were importing `primer-breadcrumbs/lib/breadcrumbs.scss` directly. Importing `primer-breadcrumbs/index.scss` is recommended because it includes the required `primer-support` file.
When changing that, the sass middleware didn't know where to find it. So adding `node_modules` to the `includePaths` for the sass middleware tells it where to look when `@import "primer-support/index.scss"` is in the css.
Adding the `includePaths` removed the need to have `@import "../node_modules/primer-breadcrumbs/...` in the `styles/index.scs` file. So I updated that also.
The rest of the `primer-css` modules are so out of date, I would recommend updating them in the same way. I could …
> Upgrade primer breadcrumbs

- bower_components/basecoat/scss/_variables.scss
- test/index.js
This is a followup to #1043 that adds a test to verify that `/styles/index.css` responds with a 200 HTTP status code. This should help prevent us from shipping stylesheet regressions in the future.
@jonrohan I see this warning show up several times in the test output:
```
WARNING: Unfortunately, no value could be retrieved from `xs`. Please make sure it is defined in `$breakpoints` map.
Backtrace:
node_modules/primer-support/lib/mixins/layout.scss:17, in mixin `breakpoint`
bower_components/basecoat/scss/_utility.scss:27
```
How would recommend solving it?
cc @broccolini
> test that the stylesheet responds with 200

- test/index.js
Tests done on `/docs/all` page had a misplaced timeout setting.
> fix: timeout setting was put in the wrong place

- data/locale.yml
- middleware/context-builder.js
- package.json
- styles/_home.scss
- styles/_variables.scss
- test/index.js
- views/home.html
Resolves #934 
This is an update to display the `latest` and `beta` version info on the homepage, instead of just `latest`.
Here's a shot at the visual:
I was also trying out using devicons for Node.js and Chromium (forgive the redundant info in this transitional screenshot):
To Do
@simurai feel free to take a turn on this PR if you have the time and energy!
> Two versions on homepage

- styles/_base.scss
- views/home.html
There's currently an unsightly scrollbar on the release version boxes :( 
(on Chrome and Safari)
> Remove scrollbar on release version info box

- data/blog/protocol-handler-fix.md
Since we followed up with a case-insensitive variant of the
original fix, the blog post's recommendations for mitigating
the fix with a new version should point to the updated fix.
> fix(blog): Bump protocol handler fix versions

- .travis.yml
Right now, greenkeeper only updates dependencies in `package.json`. This PR adds `greenkeeper-lockfile` to update `package-lock.json` too as part of the CI build process. I just followed the setup instruction for Travis [here](https://github.com/greenkeeperio/greenkeeper-lockfile#setup).
> Use greenkeeper-lockfile to update package-lock.json

- data/locale.yml
- routes/donors.js
- server.js
- views/donors.html
- views/partials/header.html
Created a `/donors` page. The contents is rendered from opencollective.com so it may or may not have a style that matches our theme at first. We can probably improve it down the road.
See: https://opencollective.com/electron
> Add OpenCollective donors page

- middleware/sass.js
I accidentally left sass in `debug` mode a while back and it was spewing output into the test results. This turns it back off. 🚒
> disable-sass-debugging

- middleware/context-builder.js
- test/index.js
Fixes 500 errors for requests like`//index.php?lang=Cn&index=0000`
> default to English if lang param is invalid

- package.json
- routes/docs/show.js
- test/index.js
- views/layouts/docs.html
This is a replacement PR for #1158, the git history of which was flummoxed. Fixes #867
At long last, this PR adds a link to the footer of every doc page that takes the user straight to the right Crowdin editor page for the given file and language.
> Translate on Crowdin

- data/blog/wordpress.md
Update the domain for the Code Signing post, redirects are currently in place but will eventually expire.
> Update link to Code Signing post

- lib/i18n.js
- test/i18n.js
This PR obfuscates email addresses in locale.yml at server startup by encoding them as HTML entities.
🍐 @codebytere
> obfuscate email addresses

- middleware/context-builder.js
- package-lock.json
- package.json
- styles/_basecoat-footer.scss
- styles/_basecoat-navigation.scss
- test/index.js
- views/layouts/main.html
- views/releases/index.html
This PR adds the [`dir`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) global attribute to the layout, and uses the `req.language` property from [express-request-langauge](https://github.com/tinganho/express-request-language) to determine direction, either `ltr` or `rtl`. This should improve the site layout for rtl languages like Arabic and Hebrew.
The stylesheet has also been updated to swap the logo and nav in the header, as well as the social links and nav in the footer.
Preview URLs
- Hebrew: https://electron-website-pr-1254.herokuapp.com/languages/he-IL
- Arabic: https://electron-website-pr-1254.herokuapp.com/languages/ar-SA
Resolves #1253 
cc @talsafran
> Support right-to-left languages

- middleware/context-builder.js
- views/layouts/docs.html
> display master branch commit for tutorials

- nodemon.json
- package-lock.json
- package.json
- scripts/lazy-load-images.js
- scripts/search.js
Hey @echjordan.
This PR does a couple things:
1. Introduces an array of `types` in search.js and iterates over them to generate all the Algolia searches (tutorials, apis, packages, apps). The actual search behavior is unchanged, this is just a refactor to reduce the amount of repeated code.
2. Speeds up development by configuring nodemon to ignore changes to frontend scripts. In development, the browserify configuration automatically regenerates the bundle on every page load, so the server doesn't need to be restarted on every change. In production, the bundle is only generated once at server startup.
> Improvements to search code

- templates/api.html
> use full signature in API search results

- CONTRIBUTING.md
- README.md
- routes/search/resolvers.js
Hi Electron Team ,
there are some spelling mistakes in some of the files :
CONTRIBUTING.md
README.md
routes/search/resolvers.js
I have fixed issue #1267 
Regards,
Kautilya
> Spelling Mistakes Fixed

- test/index.js
This test is failing on Heroku, but not locally:
```js
test('app pages apply platform labels to download links', async () => {
const $ = await get('/apps/hyper')
$('a.app-download.darwin').length.should.be.above(0)
$('a.app-download.linux').length.should.be.above(0)
$('a.app-download.win32').length.should.be.above(0)
})
```
Added some logging temporarily to see if it fails on Travis too.
> debug failing app platform label test

- scripts/search.js
We had a snippet that attempting to remove filters like `is:app` from queries, but it was having the unintended side-effect of revealing non-app results. 🤔 
So this PR disables that until we figure out a complete solution. See #1289
> remove half-baked filter removal

- cypress/integration/actions.js
- scripts/update-app-download-links.js
- views/apps/show.html
Resolves #1221 hiding sidebar "Downloads" section when no downloads available
Co-authored-by:Nhori Lopchan Tamang <nlopchantamang@hubspot.com>
Co-authored-by:Ashley Zeldin <ashley.zeldin@gmail.com>
> Hide downloads section of sidebar for apps with no downloads #1221

- script/update-deps.sh
`NODE_ENV` is set to `production` in the website config, which is causing devDependencies to be skipped when `update-electron-dependencies` runs `npm install`. This PR changes the `npm install` command to ensure all deps are installed.
> set NODE_ENV when installing to ensure production deps are installed

- package-lock.json
- package.json
Similar to https://github.com/electron/electronjs.org/pull/1325, a manual workaround to pick up 3.0.0-beta.13.
This workaround is needed due to https://github.com/electron/electronjs.org/issues/1323
> chore: manually update electron-releases to 2.80.0

- package-lock.json
- package.json
Similar to #1325 and #1327, this PR is a manual workaround to pick up the latest version of electron-releases. This time it is to get Electron 3.0.0.
This workaround is needed due to #1323
> chore: manually update electron-releases to 2.80.2

- data/blog/electron-3-0.md
Change the App Feedback Program link to the 3-0-x branch .md file, since that link should be good in perpetuity
> fix: change 404 link in blog post

- package-lock.json
- package.json
Bring 3.0 to the website manually, because the script that updates trusted deps is still misbehaving: https://github.com/electron/electronjs.org/issues/1323
> manually bump i18n module version

- lib/redirects.js
Resolves https://github.com/electron/electronjs.org/issues/1308.
This PR adds a redirect for the search result for `FAQ` that directs to `/docs/tutorial/faq`, which is a 404.
> fix: redirect broken faq in search

- scripts/search.js
> fix: hide the primary search results' container if empty

- scripts/index.js
- scripts/reset-lang-cache.js
My assumption that all content was static based on URL was incorrect, turns out our translations are done based on a cookie.  This PR updates our base JS file (which will be invalidated by the SW on reload) with some logic to wipe the SW cache whenever a locale link is followed.
There is probably a better solution with caching based on that cookie but for now this makes locale switching work again
> fix: reset SW cache on language change

- cypress/integration/actions.js
- styles/_home.scss
> fix: hide "Electron" at header on screens less 1300px

- package-lock.json
- package.json
- routes/feed/blog.js
- routes/feed/mainFeed.js
- routes/feed/releases.js
The feed was previously abstracted out but in such a way that for every request to the release endpoint, all of the releases were added to the feed again. This lead to memory leaks and errors, as seen here:
This abstracts out feed population to mitigate those errors.
/cc @MarshallOfSound
> fix: memory leak on feed construction

- scripts/service-worker.tmpl.js
Refs: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/skipWaiting
> fix: skip waiting when updating SW for instant results

- data/locale.yml
- package-lock.json
- package.json
- views/community.html
This functionality was removed in 0ef9164dd77958db17e071e71bd5d40dc67d3c4b
> chore: remove old npm package search link

- package.json
Husky scripts in the `scripts` section of `package.json` is deprecated; this moves it to its own hash.
> chore: move husky config to dedicated 'husky' hash

- data/locale.yml
- test/index.js
- views/partials/footer.html
This merely adds a link to the [LICENSE](https://github.com/electron/electron/tree/master/LICENSE). A friend of the project looked for it and couldn't find it – and we should really have it on the website.
> chore: Add a link to the license

- server.js
Prevents `express.static` and `connect-slashes` from fighting and generating infinite redirects on URLs like https://electronjs.org/node_modules/electron-apps/apps (reported by Google Analytics).
> fix: prevent infinite redirect on bad asset URLs

- script/precompile-assets.js
Changes precompiled CSS bundle size from 141K to 106K (~24% savings)
> chore: use 'compressed' output style for CSS

- data/locale.yml
- test/index.js
- views/partials/footer.html
As discussed in the meeting we just had, this PR adds a link to the security document in `electron/electron`.
> feat: Add link to security document

- data/locale.yml
- views/community.html
Tweak to the community page to make "report a security issue" easier to find:
* move it higher in the list
* replace the monkey emoji with a lock, since if you're looking for security it's visually easier to make the connection to a lock icon than a monkey icon
> feat: make 'security' slightly easier to find on the comunity page

- public/styles/_app.scss
- views/apps/index.html
| `master` | `this branch` |
| --- | --- |
| ![prev](https://user-images.githubusercontent.com/24681191/55829313-123eed00-5b17-11e9-8cef-96d10dafb6f4.png) | ![localhost_5000_apps](https://user-images.githubusercontent.com/24681191/55829321-166b0a80-5b17-11e9-86ef-d0c4f16a5413.png) |
> fix: don't show filter app bar when we on mobile

- .travis.yml
This PR disables e2e Cypress integrations tests due to this error:
> You've exceeded the limit of private test recordings under your free plan this month. The limit is 500 private test recordings.
> To continue recording tests this month you must upgrade your account. Please visit your billing to upgrade to another billing plan.
For stop block automatic PR's from Dependabot, I'm planning to disable this for some investigation.
> ci: disable e2e integration tests

- package-lock.json
- package.json
Fixes issues with Electron release timeline document.
> chore(deps): bump electron-i18n@1.1309.0

- package-lock.json
- package.json
Fixes issue with bad history on https://electronjs.org/docs/api/net-log/history and other new modules.
> chore: update electron-api-historian to v1.1.2

- data/blog/app-feedback-program.md
Due to privacy concerns, I am no longer posting check-in meeting notes in the Electron Maintainers repo.
> fix: Update app info privacy

- routes/headers.js
- server.js
- test/index.js
This PR creates a URL for downloading rebuilding assets on electron website.
- What we should do with the previous two URLs. (atom.io/download/{atom-shell, electron})
- remove? redirect?
---
Also, I want to say thanks @MarshallOfSound for creating this issue, about doing this I thought sometimes.
Fixes #2519
> feat: add Electron hosted headers redirect

- views/home.html
> Fixup from twitter.
Because:
> Fixup from other pr
Because:
Because I'm don't want to fix the bug for mobiles and create a new bug for desktops. I know this issue, I'm the creator of this issue. It's global file what uses not only on the homepage when I'm found the best option to fix this I fix this globally, but this fixes this strange global message.
Life is Strange 2
Closes #2629 
Closes #2599 
Closes #2600
> fix: add overflow-auto for homepage code block

- data/blog/electron-6-0.md
This was a last minute addition that came from a Chrome upgrade that we should include the helpers section
> chore: include the GPU helper in the 6.0 blog post

- .gitignore
- data/locale.yml
- public/styles/hljs/overrides.scss
- scripts/add-code-block-buttons.js
- scripts/copy-code-to-clipboard.js
- scripts/index.js
- views/partials/head.html
Finally the last bit to integrate a `Launch in Fiddle` button to code examples on our webpage.
The button will only be shown if the code block's `data-fiddle-url` html attribute is set (see https://github.com/electron/i18n/pull/769 for more context on how we derive that from the markdown docs).
**To use this feature**, just create a fiddle in the electron repo and add the relative path to the corresponding code block in our `/e/e` docs:
```
```javascript fiddle='{path/to/fiddle/within/e/e}'
const { app } = require('electron')
...
```
cc @felixrieseberg @erickzhao @zeke @HashimotoYT
> feat: add 'Launch in Fiddle' button to code blocks

- package-lock.json
- package.json
Reverts electron/electronjs.org#3461
It contains visible breaking changes. Should be covered by #3297.
/cc @ckerr
> build(deps): Revert "build(deps): bump @primer/css from 12.5.0 to 14.2.0"

- CONTRIBUTING.md
- data/locale.yml
- public/styles/_home.scss
- routes/home.js
- views/home.html
- views/partials/announce_banner.html
- views/partials/announcement_banner.html
This Pull Request makes announce banner more general and allows us to use them by folks for another announcement.
For using its need to change the message in `locale.yml` and update show date in `home.js`, and it's all 🙃
> Side note, should be this be documented in contrib docs?
> feat: make announce banner more general

- public/styles/helpers/_icons.scss
Fixes #3527.
The addition of `.PRIMER-REMOVE-ME` added increased CSS specificity to all `@primer/css` styles. This led to these default styles overriding our custom styles, such as `[class*="hero-octicon"]`.
This PR restores specificity for this particular style by duplicating the `[class*="hero-octicon"]` selector into a new `.PRIMER-REMOVE-ME [class*="hero-octicon"]` selector.
cc @codebytere @HashimotoYT
> fix: restore hero-octicon CSS specificity

- public/styles/_releases.scss
- public/styles/helpers/_navigation.scss
Responsiveness changes:
* Replaces manual media queries with `@include breakpoint($size)` calls to make breakpoints more uniform.
* Tweaks alignment of navbar items.
* Makes padding better for certain viewport widths.
General refactoring:
* Cuts down on `!important`.
* Moves `.menu-item` rules to the correct file (it was in `_navigation.scss` even though it only affected the Releases page).
cc @codebytere
> fix: better navbar styles

- package.json
> fix: disallow using node 14

- public/styles/_app.scss
We previously had these styles in `_home.scss`, but they're actually used on `/app`. I moved them there.
> fix: Add incorrectly deleted styles back

- data/blog/electron-9-0.md
Someone might copy-paste it to grep, for example.
> fix: a mistype in enableRemoteModule in 9.0.0 announcement

- views/apps/index.hbs
Currently, all categories on apps sidebar show as selected. That PR fix that and set the `aria-current` for only selected category. And that side effect from updating Primer to v13 or v14 😑
| Prev | Now |
| --- | --- |
| ![www electronjs org_apps](https://user-images.githubusercontent.com/24681191/87979009-0f80c500-cada-11ea-9c89-1d62e31b2282.png) | ![localhost_5000_apps](https://user-images.githubusercontent.com/24681191/87979019-14457900-cada-11ea-8c2f-7ff866cbdb3a.png) |
And how looks the selected category:
> chore: fix `aria-current` option on apps sidebar

- middleware/context-builder.js
- routes/apps/show.js
- server.js
Ref #4256 
Changes the getting of host URL from `process.env.HOST` (what seems to die) to generic style, now that support any host. And that thing can be got from `context`: `req.context.hostname` 🙀
> chore: switch from process.env.HOST to generic getting of hostname

- routes/apps/show.js
Currently, when folks post the app URL on like Twitter we show the screenshot of app or icon.
From some old-time we able to show only app screenshot, and not fallback to the icon. This PR changes this behavior and adds the ability to fallback to the icon. 
| Prev | Now |
| --- | --- |
| ![twitter com_compose_tweet (1)](https://user-images.githubusercontent.com/24681191/88090324-179e3a80-cb96-11ea-8e6d-5512b055fa23.png) | ![twitter com_compose_tweet](https://user-images.githubusercontent.com/24681191/88090253-fc332f80-cb95-11ea-9da1-115bbb64df56.png) |
> chore: fix the path to screenshot on apps show page

- CONTRIBUTING.md
- scripts/index.js
- scripts/science.js
- views/partials/doc.hbs
This PR adds the ability to use the GA Events to future analyzing the needs of features.
For usage, you need to pass `data-sc-category` and `data-sc-name` properties to element. If `data-sc-category` not passed `general` be used as a default category.
Example:
```html
<button data-sc-category="docs" data-sc-name="Something happened">Give some magic</button>
```
---
<details>
<summary>
Original PR Description
</summary>
TL;DL: I just wanna known that is useful before remove that 🤷‍♂️
So, just why not. Mainly I'm unable to make the GA events work. Also, that creates security since only we can see and maintain that data.
For usage, you need to pass `data-sc-category` and `data-sc-name` properties to element. If `data-sc-category` not passed `general` be used as a default category.
After …
> feat: add ability to use ga events for analytics

- package-lock.json
- package.json
- public/styles/index.scss
This PR replaces the `primer-support` module by the `@primer/css` import. The `hljs` imports moved because they need stuff from the `support` module like new spacers.
> refactor: switch to use `@primer/css` support

- data/locale.yml
This PR updates the link in `/community` from atomio Slack to the Discord server.
Preview: https://electron-website-pr-4589.herokuapp.com/community
> chore: update getting help section to include discord server

- views/spectron.hbs
Broke up the documentation and added highlighting to the installation instructions as requested in #4537
Let me know if this is what you were looking for.
> docs: improve spectron instructions

- views/layouts/main.hbs
Only really an issue on short pages (like the 404 page) but the footer text was overlaying on top of the search results. Moving the footer to before the search results fixes it.
> fix: ensure search hits are on top of page content

- data/blog/apple-silicon.md
Adds a blog post to land after we release Electron 11.0.0-beta.1 detailing Apple Silicon support.  A reasonable portion of this will be duplicated into the `docs` folder of `e/e` but it probably makes sense to shout about this a bit 😄
> feat: add post for apple silicon support in E11

- routes/blog/show.js
`await fs.stat` returns an exception that is not captured and thus stopping the whole process.
> fix: correctly detect if a post does not exist

- .eslintrc.js
This is a file generated by webpack and makes linting incredibly slow.
> chore: ignore webpack precompile in eslint

- views/apps/show.hbs
It looks like the way to install a cask with homebrew recently changed.
Running `brew cask install gitify`, would error with:
```
gitify > brew cask install gitify
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```
The new way of installing a cask would be by passing --cask as a flag.
```
brew install --cask gitify
```
> feat: Update command to install brew casks

- public/styles/_docs.scss
- views/layouts/docs.hbs
* Fixes padding for the table of contents navigation such that you can now see the bottom of the scrollbar when the nav overflows.
* Removes `Table of Contents` heading element.
> fix: table of contents style adjustments

- data/blog/electron-12-0.md
Small PR that adds two removed/breaking changes to the Electron blog:
- Removed Flash Support
- Required SSE3 for Chrome on x86
> chore: add Flash removal, SSE3 requirement to Electron 12 blog

- data/blog/electron-12-0.md
The Electron 12 blog describes SSE3 as Supplemental Streaming SIMD Extensions 3, but it’s actually just Streaming SIMD Extensions 3. This PR fixes the error.
> chore: remove "supplemental" from sse3

- cypress/integration/actions.js
- public/styles/_releases.scss
- views/releases/index.hbs
A couple things here:
* Adding an `<article>` tag around each set of release notes to prevent multiple `<h1>` level tags in a single page context.
* Removing stray `<h3>` tags that were placed ostensibly for visual effect.
* Making the release line menu a `<nav>`.
* Removing `style` attributes on the release line menu, instead putting them in the stylesheet.
> fix: more semantic HTML on Releases page

- data/blog/electron-13-0.md
Hilariously, Chrome published their Chrome 91 blog a few minutes after we published ours - this updates the Electron 13 blog post with a link to the Chrome 91 blog post 😄
> chore: add chrome 91 blog post

- data/locale.yml
The `discuss.atom.io` give the SSL cert error, and the http connection now redirect to the `atom/atom` repo, so it's better to remove them since we have a beautiful Discord server
> chore: remove links to `discuss.atom.io`

- cypress/integration/actions.js
- server.js
- views/home.hbs
- views/layouts/main.hbs
- views/partials/footer.hbs
- views/partials/header.hbs
- views/partials/new-docs.hbs
- views/spectron.hbs
- views/userland/spectron.hbs
Thanks to the changes in electronjs.org-new we can now generate a
direct link to the exact article a user is visiting to make the
transition from one to another easier.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Rel https://github.com/electron/electronjs.org-new/commit/cf657d5f30068b14d6d1079c0a2be7c8890ab523
> feat: add correct link to article in new site

- package.json
- server.js
- views/community.hbs
- views/home.hbs
the replace function was naive and replaced `https://discord.gg/electronjs` with `https://discord.gg/electronjsjs`
> fix: whole word only discord link replacing

- package.json
Regression from https://github.com/electron/electronjs.org/pull/5936 and Heroku doesn't let you only specify a > in the engines range.
> fix: proper node engines in package.json
